name: Global CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-solution:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.304

      - name: Restore Dependencies
        run: dotnet restore ./src/OnlineFileStrorage.sln

      - name: Build Solution
        run: dotnet build ./src/OnlineFileStrorage.sln --no-restore --configuration Release

      - name: Run All Unit Tests
        run: dotnet test ./src/OnlineFileStrorage.sln --no-build --configuration Release --verbosity normal

  build-docker:
    name:  Build ${{ matrix.service.name }}
    needs: test-solution
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: Identity Service
            file: Services/IdentityService/IdentityService.API/Dockerfile
            image: myrepo/identity-service

          - name: File API Service
            file: Services/FileApiService/FileApiService.API/Dockerfile
            image: myrepo/file-api-service

          - name: File Storage Service
            file: Services/FileStorageService/FileStorageService.API/Dockerfile
            image: myrepo/file-storage-service

          - name: API Gateway
            file: Gateway/OcelotApiGateway/Dockerfile
            image: myrepo/api-gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .  
          file: ${{ matrix.service.file }}
          push: false 
          tags: ${{ matrix.service.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max